name: Ecommerce and API Test Execution

on:
  push:
    branches: 
     - main 
     - develop

  pull_request:
    branches: 
     - main 
     - develop

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Build and run tests
      run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: target/ExtentReport.html